export const bookList = [
    {
        id:'1',
        title:'Biology 101',
        author: 'Micheal Clarke',
        category:'Biology',
        imgUrl:require('../assets/images/birds.jpeg'),
        description:'',
    },
    {
        id:'2',
        title:'Chemistry Fundamentals',
        author: 'James Boris',
        category:'Chemistry',
        imgUrl:require('../assets/images/chem.jpeg'),
        description:'',
    },
    {
        id:'3',
        title:'Physics in Action!',
        author: 'Bernie Vladimir',
        category:'Physics',
        imgUrl:require('../assets/images/newtonballs.jpeg'),
        description:'',
    },
    {
        id:'4',
        title:'African History',
        author: 'James Chike',
        category:'History',
        imgUrl:require('../assets/images/nubian.jpeg'),
        description:'',
    },
    {
        id:'5',
        title:'Human Anatomy',
        author:'Tim Berneir',
        category:'Biology',
        imgUrl:require('../assets/images/vitruvianMan.webp'),
        description:'',
    },
    {
        id:'6',
        title:'Cosmos: A Study of the universe',
        author:'James Boansi',
        category:'Physics',
        imgUrl:require('../assets/images/Cosmos.jpeg'),
        description:'',
    },
    {
        id:'7',
        title:'Engineering Marvels',
        author:'George Haddock',
        category:'Engineering',
        imgUrl:require('../assets/images/station.jpeg'),
        description:'',
    },
    {
        id:'8',
        title:'The Ancient World',
        author:'Laura Asiedu',
        category:'History',
        imgUrl:require('../assets/images/greekPainting.webp'),
        description:'',
    },
    {
        id:'9',
        title:'Earth Science',
        author:'Charles Beyuo',
        category:'Geography',
        imgUrl:require('../assets/images/geography.webp'),
        description:'',
    },
    {
        id:'10',
        title:'Our Oceans',
        author:'Hank Johnson',
        category:'Geography',
        imgUrl:require('../assets/images/ocean.jpeg'),
        description:'',
    },
    {
        id:'11',
        title:'Natural Spaces',
        author:'Kevin Adu',
        category:'Geography',
        imgUrl:require('../assets/images/amazon.jpeg'),
        description:'',
    },
    {
        id:'12',
        title:'Mechanical Engineering',
        author:'Kenneth Rivers',
        category:'Engineering',
        imgUrl:require('../assets/images/mech.jpeg'),
        description:'',
    },
    
    ]