import { models } from './models';

export const trackingAssets = [
    {
        id:'1',
        title:'Earth',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[0]],
        videoUrl:require('../assets/video/earth.mp4'),
        bookId:'6',
        bookTitle:'Cosmos: A Study of the universe',
        thumbnail:require('../assets/images/earth.jpeg'),
        lessonId:'16',
        description:"3D Model of the planet Earth. Earth is the third planet from the Sun and the only astronomical object known to harbor life. While large volumes of water can be found throughout the Solar System, only Earth sustains liquid surface water. About 71% of Earth's surface is made up of the ocean, dwarfing Earth's polar ice, lakes, and rivers. The remaining 29% of Earth's surface is land, consisting of continents and islands. Earth's surface layer is formed of several slowly moving tectonic plates, interacting to produce mountain ranges, volcanoes, and earthquakes. Earth's liquid outer core generates the magnetic field that shapes Earth's magnetosphere, deflecting destructive solar winds."
    },
    {
        id:'2',
        title:'Human Heart',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[1]],
        videoUrl:require('../assets/video/heart.mp4'),
        bookId:'1',
        thumbnail:require('../assets/images/heartThumbnail.jpeg'),
        bookTitle:'Biology 101',
        lessonId:'17',
        description:'3D Model of the human heart. The heart is a muscular organ in most animals. This organ pumps blood through the blood vessels of the circulatory system.[1] The pumped blood carries oxygen and nutrients to the body, while carrying metabolic waste such as carbon dioxide to the lungs.[2] In humans, the heart is approximately the size of a closed fist and is located between the lungs, in the middle compartment of the chest.[3]'
    },
    {
        id:'3',
        title:'Human Brain',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[2]],
        videoUrl:require('../assets/video/brain.mp4'),
        bookId:'1',
        thumbnail:require('../assets/images/brainThumbnail.jpeg'),
        bookTitle:'Biology 101',
        lessonId:'18',
        description:"3D Model of the human brain. A brain is an organ that serves as the center of the nervous system in all vertebrate and most invertebrate animals. It is located in the head, usually close to the sensory organs for senses such as vision. It is the most complex organ in a vertebrate's body. In a human, the cerebral cortex contains approximately 14–16 billion neurons,[1] and the estimated number of neurons in the cerebellum is 55–70 billion.[2] Each neuron is connected by synapses to several thousand other neurons. These neurons typically communicate with one another by means of long fibers called axons, which carry trains of signal pulses called action potentials to distant parts of the brain or body targeting specific recipient cells."
    },
    {
        id:'4',
        title:'Animal Cell',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:'',
        bookId:'1',
        thumbnail:require('../assets/images/cells.jpg'),
        bookTitle:'Biology 101',
        lessonId:'4',
        description:'3D Model of an animal cell. All animals are eukaryotic. Animal cells are distinct from those of other eukaryotes, most notably plants, as they lack cell walls and chloroplasts and have smaller vacuoles. Due to the lack of a cell wall, animal cells can transform into a variety of shapes. A phagocytic cell can even engulf other structures.'
    },
    {
        id:'5',
        title:'The Kidneys',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[1]],
        videoUrl:'',
        bookId:'5',
        thumbnail:require('../assets/images/assetImages/kidney.jpeg'),
        bookTitle:'Human Anatomy',
        lessonId:'6',
        description:'3D Model of a kidney. The kidneys are two reddish-brown bean-shaped organs found in vertebrates. They are located on the left and right in the retroperitoneal space, and in adult humans are about 12 centimetres (4+1⁄2 inches) in length.[1][2] They receive blood from the paired renal arteries; blood exits into the paired renal veins. Each kidney is attached to a ureter, a tube that carries excreted urine to the bladder.'
    },
    {
        id:'6',
        title:'The Liver',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[4]],
        videoUrl:require('../assets/video/liver.mp4'),
        bookId:'5',
        thumbnail:require('../assets/images/assetImages/liver.png'),
        bookTitle:'Human Anatomy',
        lessonId:'7',
        description:'3D Model of the Liver. The liver is a major organ only found in vertebrates which performs many essential biological functions such as detoxification of the organism, and the synthesis of proteins and biochemicals necessary for digestion and growth.'
    },
    {
        id:'7',
        title:'The Skin',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:'',
        bookId:'5',
        thumbnail:require('../assets/images/assetImages/skin.png'),
        bookTitle:'Human Anatomy',
        lessonId:'8',
        description:'3D Model of Human Skin. Skin is the layer of usually soft, flexible outer tissue covering the body of a vertebrate animal, with three main functions: protection, regulation, and sensation.'
    },
    {
        id:'8',
        title:'The Digestive System',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/digestiveSystem.mp4'),
        bookId:'5',
        thumbnail:require('../assets/images/assetImages/git.png'),
        bookTitle:'Human Anatomy',
        lessonId:'9',
        description:'3D Model of the digestive system. The human digestive system consists of the gastrointestinal tract plus the accessory organs of digestion (the tongue, salivary glands, pancreas, liver, and gallbladder). Digestion involves the breakdown of food into smaller and smaller components, until they can be absorbed and assimilated into the body.'
    },
    {
        id:'9',
        title:'The Airways',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:'',
        bookId:'5',
        thumbnail:require('../assets/images/assetImages/lungs.png'),
        bookTitle:'Human Anatomy',
        lessonId:'10',
        description:'3D Model of the respiratory system. The respiratory tract is the subdivision of the respiratory system involved with the process of respiration in mammals.[1] The respiratory tract is lined with respiratory epithelium as respiratory mucosa.[2]'
    },
    {
        id:'10',
        title:'Mercury',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/mercury.mp4'),
        bookId:'6',
        thumbnail:require('../assets/images/assetImages/mercury.jpg'),
        bookTitle:'Cosmos: A Study of the universe',
        lessonId:'11',
        description:"Mercury is the smallest planet in the Solar System and the closest to the Sun. Its orbit around the Sun takes 87.97 Earth days, the shortest of all the Sun's planets."
    },
    {
        id:'11',
        title:'Venus',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/venus.mp4'),
        bookId:'6',
        thumbnail:require('../assets/images/assetImages/venus.png'),
        bookTitle:'Cosmos: A Study of the universe',
        lessonId:'12',
        description:"Venus is the second planet from the Sun. It is sometimes called Earth's 'sister' or 'twin' planet as it is almost as large and has a similar composition. As an interior planet to Earth, Venus (like Mercury) appears in Earth's sky never far from the Sun, either as morning star or evening star. Aside from the Sun and Moon, Venus is the brightest natural object in Earth's sky, capable of casting visible shadows on Earth at dark conditions and being visible to the naked eye in broad daylight.[18][19]"
    },
    {
        id:'12',
        title:'Mars',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/mars.mp4'),
        bookId:'6',
        thumbnail:require('../assets/images/assetImages/mars.png'),
        bookTitle:'Cosmos: A Study of the universe',
        lessonId:'13',
        description:"Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System, being larger than only Mercury. In the English language, Mars is named for the Roman god of war. Mars is a terrestrial planet with a thin atmosphere (less than 1% that of Earth's), and has a crust primarily composed of elements similar to Earth's crust, as well as a core made of iron and nickel. Mars has surface features such as impact craters, valleys, dunes, and polar ice caps. It has two small and irregularly shaped moons: Phobos and Deimos."
    },
    {
        id:'13',
        title:'Jupiter',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/jupiter.mp4'),
        bookId:'6',
        thumbnail:require('../assets/images/assetImages/jupiter.jpg'),
        bookTitle:'Cosmos: A Study of the universe',
        lessonId:'14',
        description:"Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass more than two and a half times that of all the other planets in the Solar System combined, but slightly less than one-thousandth the mass of the Sun. Jupiter is the third brightest natural object in the Earth's night sky after the Moon and Venus, and it has been observed since prehistoric times. It was named after the Roman god Jupiter, the king of the gods.]"
    },
    {
        id:'14',
        title:'Saturn',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/saturn.mp4'),
        bookId:'6',
        thumbnail:require('../assets/images/assetImages/saturn.jpg'),
        bookTitle:'Cosmos: A Study of the universe',
        lessonId:'15',
        description:"Saturn is the sixth planet from the Sun and the second-largest in the Solar System, after Jupiter. It is a gas giant with an average radius of about nine and a half times that of Earth.[23][24] It has only one-eighth the average density of Earth; however, with its larger volume, Saturn is over 95 times more massive.[25][26][27]",
    },
    {
        id:'15',
        title:'International Space Station',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/spacestation.mp4'),
        bookId:'7',
        thumbnail:require('../assets/images/station.jpeg'),
        bookTitle:'Engineering Marvels',
        lessonId:'19',
        description:"The International Space Station (ISS) is the largest modular space station currently in low Earth orbit. It is a multinational collaborative project involving five participating space agencies: NASA (United States), Roscosmos (Russia), JAXA (Japan), ESA (Europe), and CSA (Canada).[8][9] The ownership and use of the space station is established by intergovernmental treaties and agreements.[10] The station serves as a microgravity and space environment research laboratory in which scientific research is conducted in astrobiology, astronomy, meteorology, physics, and other fields.",
    },
    {
        id:'16',
        title:'The Wright Flyer',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/wrightFlyer.mp4'),
        bookId:'7',
        thumbnail:require('../assets/images/wright.jpeg'),
        bookTitle:'Engineering Marvels',
        lessonId:'21',
        description:"The Wright Flyer (also known as the Kitty Hawk,[3][4] Flyer I or the 1903 Flyer) made the first sustained flight by a manned heavier-than-air powered and controlled aircraft—an airplane—on 17 December 1903.",
    },
    {
        id:'17',
        title:'The Space Shuttle',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/spaceShuttle.mp4'),
        bookId:'7',
        thumbnail:require('../assets/images/spaceShuttle.jpeg'),
        bookTitle:'Engineering Marvels',
        lessonId:'20',
        description:"The Space Shuttle is a retired, partially reusable low Earth orbital spacecraft system operated from 1981 to 2011 by the U.S. National Aeronautics and Space Administration (NASA) as part of the Space Shuttle program. Its official program name was Space Transportation System (STS), taken from a 1969 plan for a system of reusable spacecraft where it was the only item funded for development.[7] The first (STS-1) of four orbital test flights occurred in 1981, leading to operational flights (STS-5) beginning in 1982. Five complete Space Shuttle orbiter vehicles were built and flown on a total of 135 missions from 1981 to 2011. ",
    },
    {
        id:'18',
        title:'The Pantheon',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/rome.mp4'),
        bookId:'8',
        thumbnail:require('../assets/images/pantheon.jpeg'),
        bookTitle:'The Ancient World',
        lessonId:'22',
        description:"The Pantheon (UK: /ˈpænθiən/, US: /-ɒn/;[1] Latin: Pantheum,[nb 1] from Greek Πάνθειον Pantheion, '[temple] of all the gods') is a former Roman temple and, since 609 AD, a Catholic church (Basilica di Santa Maria ad Martyres or Basilica of St. Mary and the Martyrs) in Rome, Italy, on the site of an earlier temple commissioned by Marcus Agrippa during the reign of Augustus (27 BC – 14 AD). It was rebuilt by the emperor Hadrian and probably dedicated c. 126 AD. Its date of construction is uncertain, because Hadrian chose not to inscribe the new temple but rather to retain the inscription of Agrippa's older temple, which had burned down.[2]",
    },

    {
        id:'19',
        title:'The Acropolis',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:'',
        bookId:'8',
        thumbnail:require('../assets/images/acropolis.jpeg'),
        bookTitle:'The Ancient World',
        lessonId:'24',
        description:"The Acropolis of Athens is an ancient citadel located on a rocky outcrop above the city of Athens and contains the remains of several ancient buildings of great architectural and historical significance, the most famous being the Parthenon. The word acropolis is from the Greek words ἄκρον (akron, 'highest point, extremity') and πόλις (polis, 'city').[1] The term acropolis is generic and there are many other acropoleis in Greece. During ancient times the Acropolis of Athens was known also more properly as Cecropia, after the legendary serpent-man, Cecrops, the supposed first Athenian king.",
    },
    {
        id:'20',
        title:'Kokura Castle',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:'',
        bookId:'8',
        thumbnail:require('../assets/images/himejiCastle.jpeg'),
        bookTitle:'The Ancient World',
        lessonId:'25',
        description:"Kokura Castle is a castle in Kitakyushu, Japan. It was built by Hosokawa Tadaoki starting in 1602, with construction completed in 1608. ",
    },
    {
        id:'21',
        title:'King Tutankhamun',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:'',
        bookId:'8',
        thumbnail:require('../assets/images/pharoah.jpeg'),
        bookTitle:'The Ancient World',
        lessonId:'23',
        description:"Tutankhamun, Egyptological pronunciation Tutankhamen, sometimes referred to as King Tut, was an Egyptian pharaoh who was the last of his royal family to rule during the end of the Eighteenth Dynasty during the New Kingdom of Egyptian history.",
    },
    {
        id:'22',
        title:'The Command Module',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:'',
        bookId:'7',
        thumbnail:require('../assets/images/commandModule.jpeg'),
        bookTitle:'Engineering Marvels',
        lessonId:'26',
        description:"Command module Columbia (CM-107) is the spacecraft that served as the command module during Apollo 11, which was the first mission to land humans on the Moon. Columbia is the only spacecraft of the 1969 Apollo 11 mission that returned to Earth.[1][2]",
    },

    {
        id:'23',
        title:'Yoruba Head Sculpture',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:'',
        bookId:'4',
        thumbnail:require('../assets/images/yoruba.jpeg'),
        bookTitle:'African History',
        lessonId:'27',
        description:"An Epa mask is a ceremonial mask worn by the Yoruba people of Nigeria during the Epa masquerade. Carvings representing priests, hunters, farmers, kings, and mothers are usually depicted on the masks.",
    },
    {
        id:'24',
        title:'Coral',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/coralreefs.mp4'),
        bookId:'10',
        thumbnail:require('../assets/images/coral1.jpeg'),
        bookTitle:'Our Oceans',
        lessonId:'29',
        description:"Corals are marine invertebrates within the class Anthozoa of the phylum Cnidaria. They typically form compact colonies of many identical individual polyps. Coral species include the important reef builders that inhabit tropical oceans and secrete calcium carbonate to form a hard skeleton.",
    },
    {
        id:'25',
        title:'The Himalayas',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/everest.mp4'),
        bookId:'9',
        thumbnail:require('../assets/images/himalayas2.webp'),
        bookTitle:'Earth Science',
        lessonId:'28',
        description:"The Himalayas, or Himalaya (/ˌhɪməˈleɪ.ə, hɪˈmɑːləjə/; Sanskrit: [ɦɪmaːlɐjɐ]; from Sanskrit himá 'snow, frost', and ā-laya 'dwelling, abode'),[1] is a mountain range in Asia, separating the plains of the Indian subcontinent from the Tibetan Plateau. The range has some of the planet's highest peaks, including the very highest, Mount Everest in Nepal. Over 100 peaks exceeding 7,200 m (23,600 ft) in elevation lie in the Himalayas. By contrast, the highest peak outside Asia (Aconcagua, in the Andes) is 6,961 m (22,838 ft) tall.[2]",
    },
    // {
    //     id:'26',
    //     title:'Carbon Model',
    //     imgUrl:require('../assets/images/trackerMain.png'),
    //     models:[models[3]],
        // videoUrl:'',
    //     bookId:'2',
    //     thumbnail:require('../assets/images/carbon.jpeg'),
    //     bookTitle:'Chemistry Fundamentals',
    //     lessonId:'30',
    //     description:"Carbon (from Latin carbo 'coal') is a chemical element with the symbol C and atomic number 6. It is nonmetallic and tetravalent—its atom making four electrons available to form covalent chemical bonds. It belongs to group 14 of the periodic table.[14] Carbon makes up only about 0.025 percent of Earth's crust.[15] Three isotopes occur naturally, 12C and 13C being stable, while 14C is a radionuclide, decaying with a half-life of about 5,730 years.[16] Carbon is one of the few elements known since antiquity.[17]",
    // },
    {
        id:'27',
        title:'Hydrogen Model',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/hydrogen.mp4'),
        bookId:'2',
        thumbnail:require('../assets/images/hydrogen.jpeg'),
        bookTitle:'Chemistry Fundamentals',
        lessonId:'31',
        description:"Hydrogen is the chemical element with the symbol H and atomic number 1. Hydrogen is the lightest element. At standard conditions hydrogen is a gas of diatomic molecules having the formula H2. It is colorless, odorless, tasteless,[8] non-toxic, and highly combustible. Hydrogen is the most abundant chemical substance in the universe, constituting roughly 75% of all normal matter.[9][note 1] Stars such as the Sun are mainly composed of hydrogen in the plasma state. Most of the hydrogen on Earth exists in molecular forms such as water and organic compounds. For the most common isotope of hydrogen (symbol 1H) each atom has one proton, one electron, and no neutrons.",
    },
    
    {
        id:'28',
        title:'Helium Model',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/helium.mp4'),
        bookId:'2',
        thumbnail:require('../assets/images/Helium.jpg'),
        bookTitle:'Chemistry Fundamentals',
        lessonId:'32',
        description:"Helium (from Greek: ἥλιος, romanized: helios, lit. 'sun') is a chemical element with the symbol He and atomic number 2. It is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas and the first in the noble gas group in the periodic table.[a] Its boiling and melting point are the lowest among all the elements. It is the second lightest and second most abundant element in the observable universe (hydrogen is the lightest and most abundant). It is present at about 24% of the total elemental mass, which is more than 12 times the mass of all the heavier elements combined. Its abundance is similar to this in both the Sun and in Jupiter, due to the very high nuclear binding energy (per nucleon) of helium-4, with respect to the next three elements after helium. This helium-4 binding energy also accounts for why it is a product of both nuclear fusion and radioactive decay. The most common isotope of helium in the universe is helium-4, the vast majority of which was formed during the Big Bang. Large amounts of new helium are created by nuclear fusion of hydrogen in stars.",
    },
    {
        id:'29',
        title:'Lithium Model',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/lithium.mp4'),
        bookId:'2',
        thumbnail:require('../assets/images/lithium.png'),
        bookTitle:'Chemistry Fundamentals',
        lessonId:'33',
        description:"Lithium (from Greek: λίθος, romanized: lithos, lit. 'stone') is a chemical element with the symbol Li and atomic number 3. It is a soft, silvery-white alkali metal. Under standard conditions, it is the least dense metal and the least dense solid element. Like all alkali metals, lithium is highly reactive and flammable, and must be stored in vacuum, inert atmosphere, or inert liquid such as purified kerosene or mineral oil. When cut, it exhibits a metallic luster, but moist air corrodes it quickly to a dull silvery gray, then black tarnish. It never occurs freely in nature, but only in (usually ionic) compounds, such as pegmatitic minerals, which were once the main source of lithium. Due to its solubility as an ion, it is present in ocean water and is commonly obtained from brines. Lithium metal is isolated electrolytically from a mixture of lithium chloride and potassium chloride.",
    },
    {
        id:'30',
        title:'Saturn V',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/saturnV.mp4'),
        bookId:'7',
        thumbnail:require('../assets/images/saturnV.jpeg'),
        bookTitle:'Engineering Marvels',
        lessonId:'26',
        description:"Saturn V is a retired American super heavy-lift launch vehicle developed by NASA under the Apollo program for human exploration of the Moon. ",
    },
    {
        id:'31',
        title:'Olympus Mons',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:'',
        bookId:'6',
        thumbnail:require('../assets/images/saturnV.jpeg'),
        bookTitle:'Cosmos: A Study of the universe',
        lessonId:'13',
        description:"Olympus Mons is a large shield volcano on Mars. The volcano has a height of over 21.9 km as measured by the Mars Orbiter Laser Altimeter.",
    },
    {
        id:'32',
        title:'Canyon Model',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/canyon.mp4'),
        bookId:'9',
        thumbnail:require('../assets/images/canyon.jpeg'),
        bookTitle:'Earth Science',
        lessonId:'34',
        description:"Grand Canyon National Park, in Arizona, is home to much of the immense Grand Canyon, with its layered bands of red rock revealing millions of years of geological history.",
    },
    {
        id:'33',
        title:'Uranus',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/uranus.mp4'),
        bookId:'6',
        thumbnail:require('../assets/images/uranus.jpeg'),
        bookTitle:'Cosmos: A Study of the universe',
        lessonId:'36',
        description:"Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass more than two and a half times that of all the other planets in the Solar System combined, but slightly less than one-thousandth the mass of the Sun. Jupiter is the third brightest natural object in the Earth's night sky after the Moon and Venus, and it has been observed since prehistoric times. It was named after the Roman god Jupiter, the king of the gods.]"
    },
    {
        id:'34',
        title:'Neptune',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/neptune.mp4'),
        bookId:'6',
        thumbnail:require('../assets/images/neptune.jpeg'),
        bookTitle:'Cosmos: A Study of the universe',
        lessonId:'35',
        description:"Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass more than two and a half times that of all the other planets in the Solar System combined, but slightly less than one-thousandth the mass of the Sun. Jupiter is the third brightest natural object in the Earth's night sky after the Moon and Venus, and it has been observed since prehistoric times. It was named after the Roman god Jupiter, the king of the gods.]"
    },
    {
        id:'35',
        title:'Bosomtwe Model',
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/neptune.mp4'),
        bookId:'9',
        thumbnail:require('../assets/images/bosomtwe.jpeg'),
        bookTitle:'Earth Science',
        lessonId:'37',
        description:"Lake Bosumtwi is the only natural lake in Ghana. It is situated within an ancient impact crater that is about 10.5 kilometres (6.5 mi) in diameter.[2] It is about 30 km (19 mi) south-east of Kumasi, the capital of Ashanti, and is a popular recreational area."
    },
    {
        id:'36',
        title:"Akua'ba Sculpture",
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/akuaba.mp4'),
        bookId:'9',
        thumbnail:require('../assets/images/ashanti.jpeg'),
        bookTitle:'African History',
        lessonId:'38',
        description:"Akua'ba (sometimes spelled Akwaba or Akuba) are wooden ritual fertility dolls from Southern Ghana and nearby areas. The best known akua'ba are those of the Fanti people, “Fanti Dolls” whose akua'ba have large, disc-like heads. Other tribes in the West Africa region (f.ex. Kru and Igbo people) have their own distinctive style of akua'ba. Traditionally, these dolls are carried on the back of young women either hoping to conceive a child, or to ensure the attractiveness of the child being carried. When not in active use, the akua'ba would be ritually washed and cared for in the traditional homestead. The treatment of the Akua'ba has been described as an example of traditional beliefs that corresponds to many traditional beliefs in West African sympathetic magic.[1]"
    },

    {
        id:'37',
        title:"Carbon Model",
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/carbon.mp4'),
        bookId:'2',
        thumbnail:require('../assets/images/carbon.jpeg'),
        bookTitle:'Chemistry Fundamentals',
        lessonId:'30',
        description:"Carbon (from Latin carbo 'coal') is a chemical element with the symbol C and atomic number 6. It is nonmetallic and tetravalent—its atom making four electrons available to form covalent chemical bonds. It belongs to group 14 of the periodic table.[14] Carbon makes up about 0.025 percent of Earth's crust.[15] Three isotopes occur naturally, 12C and 13C being stable, while 14C is a radionuclide, decaying with a half-life of about 5,730 years.[16] Carbon is one of the few elements known since antiquity.[17]"
    },
    {
        id:'38',
        title:"Glacier Model",
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/glacier.mp4'),
        bookId:'9',
        thumbnail:require('../assets/images/glaciers.jpeg'),
        bookTitle:'Earth Science',
        lessonId:'39',
        description:"A glacier (US: /ˈɡleɪʃər/; UK: /ˈɡlæsiər, ˈɡleɪsiər/) is a persistent body of dense ice that is constantly moving under its own weight. A glacier forms where the accumulation of snow exceeds its ablation over many years, often centuries. It acquires distinguishing features, such as crevasses and seracs, as it slowly flows and deforms under stresses induced by its weight. As it moves, it abrades rock and debris from its substrate to create landforms such as cirques, moraines, or fjords. Although a glacier may flow into a body of water, it forms only on land and is distinct from the much thinner sea ice and lake ice that form on the surface of bodies of water."
    },
    {
        id:'39',
        title:"Bora Bora Islands",
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/archipelago.mp4'),
        bookId:'9',
        thumbnail:require('../assets/images/islands.webp'),
        bookTitle:'Earth Science',
        lessonId:'40',
        description:"An island (or isle) is an isolated piece of habitat that is surrounded by a dramatically different habitat, such as water."
    },
    {
        id:'40',
        title:"Hurricane Harvey",
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/hurricane.mp4'),
        bookId:'10',
        thumbnail:require('../assets/images/storm.jpeg'),
        bookTitle:'Our Oceans',
        lessonId:'41',
        description:"Hurricane Harvey was a devastating Category 4 hurricane that made landfall on Texas and Louisiana in August 2017, causing catastrophic flooding and more than 100 deaths. It is tied with 2005's Hurricane Katrina as the costliest tropical cyclone on record,[nb 1] inflicting $125 billion (2017 USD) in damage, primarily from catastrophic rainfall-triggered flooding in the Houston metropolitan area and Southeast Texas;[1][2] this made the storm the costliest natural disaster recorded in Texas at the time.[3]"
    },
    {
        id:'41',
        title:"Amazon Rainforest Model",
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/amazon.mp4'),
        bookId:'11',
        thumbnail:require('../assets/images/amazon.jpeg'),
        bookTitle:'Natural Spaces',
        lessonId:'42',
        description:"The Amazon rainforest, Amazon jungle[a] or Amazonia is a moist broadleaf tropical rainforest in the Amazon biome that covers most of the Amazon basin of South America. This basin encompasses 7,000,000 km2 (2,700,000 sq mi), of which 5,500,000 km2 (2,100,000 sq mi) are covered by the rainforest. This region includes territory belonging to nine nations and 3,344 formally acknowledged indigenous territories."
    },
    {
        id:'42',
        title:"V8 Engine Model",
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/v8.mp4'),
        bookId:'12',
        thumbnail:require('../assets/images/v8.webp'),
        bookTitle:'Mechanical Engineering',
        lessonId:'43',
        description:"A V8 engine is an eight-cylinder piston engine in which two banks of four cylinders share a common crankshaft and are arranged in a V configuration.[1]"
    },
    {
        id:'43',
        title:"Turbofan Engine",
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/v8.mp4'),
        bookId:'12',
        thumbnail:require('../assets/images/turbofan.jpeg'),
        bookTitle:'Mechanical Engineering',
        lessonId:'45',
        description:"A V8 engine is an eight-cylinder piston engine in which two banks of four cylinders share a common crankshaft and are arranged in a V configuration.[1]"
    },
    {
        id:'44',
        title:"Simple Nuclear Reactor",
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/v8.mp4'),
        bookId:'3',
        thumbnail:require('../assets/images/reactor.jpeg'),
        bookTitle:'Physics in Action!',
        lessonId:'46',
        description:"A V8 engine is an eight-cylinder piston engine in which two banks of four cylinders share a common crankshaft and are arranged in a V configuration.[1]"
    },
    {
        id:'45',
        title:"Thermal Power Station",
        imgUrl:require('../assets/images/trackerMain.png'),
        models:[models[3]],
        videoUrl:require('../assets/video/v8.mp4'),
        bookId:'3',
        thumbnail:require('../assets/images/thermalPlant.jpeg'),
        bookTitle:'Physics in Action!',
        lessonId:'47',
        description:"A V8 engine is an eight-cylinder piston engine in which two banks of four cylinders share a common crankshaft and are arranged in a V configuration.[1]"
    },
    
    




    
]